AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function extension for logging to Coralogix.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Coralogix-Lambda-Extension
    Description: Lambda function extension for logging to Coralogix.
    Author: Coralogix
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
      - coralogix
      - logs
      - lambda
      - extension
    HomePageUrl: https://coralogix.com
    SemanticVersion: 1.0.5
    SourceCodeUrl: https://github.com/coralogix/aws-lambda-extension
Parameters:
  CompatibleRuntimes:
    Type: CommaDelimitedList
    Description: Lambda Layer Version compatible runtimes
    Default: go1.x, nodejs12.x, nodejs14.x, python3.8, python3.9
  RetentionPolicy:
    Type: String
    Description: Lambda Layer Version retention policy
    AllowedValues:
      - Retain
      - Delete
    Default: Retain
Resources:
  LambdaLayerAMD64Version:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: coralogix-extension-x86_64
      Description: Lambda function extension for logging to Coralogix (x86_64)
      LicenseInfo: Apache-2.0
      ContentUri: ./layers/layer-x86_64.zip
      CompatibleRuntimes:
        Ref: CompatibleRuntimes
      CompatibleArchitectures:
        - x86_64
      RetentionPolicy:
        Ref: RetentionPolicy
  LambdaLayerARM64Version:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: coralogix-extension-arm64
      Description: Lambda function extension for logging to Coralogix (arm64)
      LicenseInfo: Apache-2.0
      ContentUri: ./layers/layer-arm64.zip
      CompatibleRuntimes:
        Ref: CompatibleRuntimes
      CompatibleArchitectures:
        - arm64
      RetentionPolicy:
        Ref: RetentionPolicy
Outputs:
  LambdaLayerAMD64VersionArn:
    Description: Lambda Layer version ARN for coralogix-extension (x86_64)
    Value:
      Ref: LambdaLayerAMD64Version
    Export:
      Name: CORALOGIX-EXTENSION-AMD64
  LambdaLayerARM64VersionArn:
    Description: Lambda Layer version ARN for coralogix-extension (arm64)
    Value:
      Ref: LambdaLayerARM64Version
    Export:
      Name: CORALOGIX-EXTENSION-ARM64
